### ISSUE TITLE
Error in the example for the gscaLCA  function

### ISSUE THREAD

**Issue by jacobkap** [hee6904/gscaLCA#2]
When running the example code for the gscaLCA  function, R returns an error (see image). I am using the gscaLCA package currently available on CRAN and using R version 4.0.2 on a Windows 10 machine. 

![error](https://user-images.githubusercontent.com/15526406/98492813-97f8b200-21fe-11eb-9f97-644581e38af4.PNG)

**Comment by jacobkap** [comment]
I have updated the fastDummies dev version to fix this issue.

**Comment by hee6904** [comment]
Thanks a lot!
